target_sources(${PROJECT_NAME}${EXECUTABLE_SUFFIX}
PRIVATE
  ${CMAKE_CURRENT_LIST_DIR}/${CCS_PROJECT_LINK}/${SYSCONFIG_TYPE}/syscfg/ti_drivers_config.c
  ${CMAKE_CURRENT_LIST_DIR}/${CCS_PROJECT_LINK}/${SYSCONFIG_TYPE}/syscfg/ti_freertos_config.c
  ${CMAKE_CURRENT_LIST_DIR}/${CCS_PROJECT_LINK}/${SYSCONFIG_TYPE}/syscfg/ti_freertos_portable_config.c
)

target_include_directories(${PROJECT_NAME}${EXECUTABLE_SUFFIX}
PRIVATE
  ${CMAKE_CURRENT_LIST_DIR}/FreeRTOS/FreeRTOS/Source
  ${CMAKE_CURRENT_LIST_DIR}/FreeRTOS/FreeRTOS/Source/include
  ${CMAKE_CURRENT_LIST_DIR}/FreeRTOS/FreeRTOS/Source/portable/${PORT}
  ${CMAKE_CURRENT_LIST_DIR}/${CCS_PROJECT_LINK}/${SYSCONFIG_TYPE}/syscfg
)

target_link_libraries(${PROJECT_NAME}${EXECUTABLE_SUFFIX}
PRIVATE
    #Required libraries can be found in the linker file generated by sysconfig.
    ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/display/lib/gcc/m4/display_cc32xx.a
    ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/drivers/lib/gcc/m4/drivers_cc32xx.a
    ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/devices/cc32xx/driverlib/gcc/Release/driverlib.a
    ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/grlib/lib/gcc/m4/grlib.a
)

target_include_directories(${PROJECT_NAME}${EXECUTABLE_SUFFIX} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/kernel/freertos)
target_include_directories(${PROJECT_NAME}${EXECUTABLE_SUFFIX} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/)
target_include_directories(${PROJECT_NAME}${EXECUTABLE_SUFFIX} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/posix/freertos)
target_include_directories(${PROJECT_NAME}${EXECUTABLE_SUFFIX} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/drivers/)
target_include_directories(${PROJECT_NAME}${EXECUTABLE_SUFFIX} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/${SDK_LINK}/source/ti/posix/gcc)
target_compile_definitions(${PROJECT_NAME}${EXECUTABLE_SUFFIX} PRIVATE DeviceFamily_CC3220 _REENT_SMALL)

#This does not belong here. Should go in CMakeLists.txt
add_custom_command(TARGET ${PROJECT_NAME}${EXECUTABLE_SUFFIX} POST_BUILD
COMMAND
  ${CMAKE_OBJCOPY} ARGS -O binary ${CMAKE_SOURCE_DIR}/customToolchain_build/${PROJECT_NAME}${EXECUTABLE_SUFFIX} ${CMAKE_SOURCE_DIR}/customToolchain_build/${PROJECT_NAME}.bin
  WORKING_DIRECTORY
    ${CMAKE_CURRENT_LIST_DIR}
  COMMENT
    "Stripping executable"
  VERBATIM
)
